config/routes.rb
AnthroSite::Application.routes.draw do
  root to: "static_pages#home"
  get "/home", to: "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/help", to: "static_pages#help"
  get "/news", to: "static_pages#news"
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def help
  end
  
  def news
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(title = "")
    if title.empty?
      "Anthropomorphic"
    else
      "Anthropomorphic | #{title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "News", news_path %></li>
    </ul>
  </nav>
  
  <div class="well-small">
    <div class="well well-small" id="powered-by">
      Powered by:
      <%= link_to image_tag("rails_gray.png", alt: "Rails", width: 25, id: "rails-icon"), 'http://rubyonrails.org/' %>
    </div>
  </div>

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Anthropomorphic", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide :page_title, "About" %>

<div class="hero-unit center">
  <h1>About Me:</h1>
  <p>
    My name is Michael Dorst, though I often go by anthropomorphic on the internet.<br>
    I'm a software developer, mostly in web right now. I started programming in C++ in 2010,
    but in 2012 I started playing with <a href="http://ruby-lang.org/en/">Ruby</a> and promptly fell in love.
    Since then I've been playing with web development in <a href="http://rubyonrails.org">Rails</a>, and absolutely loving it.
    It's a great platform that makes programming fun.<br>
    I'm a big fan of <a href="http://github.com">GitHub</a>, <a href="http://c9.io">Cloud9</a> and <a href="http://stackoverflow.com">Stack Overflow</a>.<br>
    All the projects I'm currently working on are located <a href="http://github.com/anthropomorphic">here</a>,
    at my GitHub page.
  </p>
</div>

app/views/static_pages/contact.html.erb
<% provide :page_title, "Contact" %>

<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/help.html.erb
<% provide :page_title, "Help" %>

<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide :page_title, "Home" %>

<div class="center hero-unit">
  <h1>Welcome</h1>

  <h2>
    This is the home page of <%= link_to "Michael Dorst", about_path %>.
  </h2>
  
</div>

app/views/static_pages/news.html.erb
<h1>StaticPages#news</h1>
<p>Find me in app/views/static_pages/news.html.erb</p>